name: Build

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        ruby_version:
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
        gemfile:
          - gemfiles/selenium_webdriver_4_1.gemfile
          - gemfiles/selenium_webdriver_4_0.gemfile
          - gemfiles/selenium_webdriver_3.gemfile
          - gemfiles/cuprite.gemfile
    runs-on: ubuntu-22.04
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: bundle exec rake test

  edge:
    runs-on: ubuntu-22.04
    env:
      BUNDLE_GEMFILE: gemfiles/selenium_webdriver_4_1.gemfile
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      - run: bundle exec rake test
        env:
          TARGET_BROWSER: 'Windows, 11, Edge, latest'
          BROWSERSTACK_URL: "${{ secrets.BROWSERSTACK_URL }}"

  safari:
    runs-on: ubuntu-22.04
    env:
      BUNDLE_GEMFILE: gemfiles/selenium_webdriver_4_1.gemfile
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      - run: bundle exec rake test
        env:
          TARGET_BROWSER: 'OS X, Monterey, Safari, latest'
          BROWSERSTACK_URL: '${{ secrets.BROWSERSTACK_URL }}'

  firefox:
    runs-on: ubuntu-22.04
    env:
      BUNDLE_GEMFILE: gemfiles/selenium_webdriver_4_1.gemfile
      JS_DRIVER: selenium_headless
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
          bundler-cache: true
      - run: bundle exec rake test || echo "Firefox test is done."
